---

- debug: msg="Installing Ansible"

- name: install pip
  easy_install: name=pip 
                state=latest

- name: Upgrade to latest version of pip.
  pip: name=pip
       state=latest

- name: install ansible
  pip: name=ansible
       version=2.1.2.0
       state=present
       